# i2pd (I2P Daemon)
# https://i2pd.readthedocs.io/en/latest/user-guide/install/#docker-images

#FROM purplei2p/i2pd
FROM purplei2p/i2pd:release-2.43.0
COPY i2pd.conf /home/i2pd/data/
COPY tunnels.conf /home/i2pd/data/